### ISSUE TITLE
ES2015 transpiling into ES3.

### ISSUE THREAD

**Issue by fshafique** [Trackhe/kitematic#3]
I examined your solution to the No Logging problem with Kitematic - a little bit of code change in the `/utils/DockerUtil.js` file.  I also extracted the `app.asar` file to examine the transpiled version of the same file. It seems all the **let**s are transpiled into **var**s.

I suspect that was **not** the intention of the developers. I'm no expert, but I suspect the `tsconfig.json` file has two mentions of `es2015`, where it is supposed to be case-sensitive all-caps `ES2015`.

Can I implore you to test this out? I would do it myself, but I'm resisting the urge to deep dive into yet another project. Thanks. 

Reference:
- [TypeScript Compiler Options](https://www.typescriptlang.org/docs/handbook/compiler-options.html)
- [Should the keys to `tsconfig` be case insensitive](https://github.com/Microsoft/TypeScript/issues/1933)

**Comment by Trackhe** [comment]
@fshafique I will test that. Thank you for your commitment. I will give you a response.

**Comment by Trackhe** [comment]
I close this because i fix it already without any downgrade. https://github.com/Trackhe/kitematic/commit/0e2535e9f3c20f4b96c31c19cc5baf8c3bbf33b9
I review the options but. not needed. Thank you for your commitment.
