### ISSUE TITLE
Wrong link to ../share/kitematic/KitematicnonOriginal in Deb install

### ISSUE THREAD

**Issue by PhoneixS** [Trackhe/kitematic#4]
### Expected behavior

Deb installer should create a functional link `/usr/bin/kitematic` to `../share/kitematic/Kitematic`.

### Actual behavior

The installation from the deb file makes a link `/usr/bin/kitematic` to `../share/kitematic/KitematicnonOriginal`.

### Information about the Issue

The deb creates a link with an invalid target.

### Steps to reproduce the behavior

  1. Install the deb file in `Kitematic-0.17.11-Debian-Ubuntu.zip` with `sudo apt install ./Kitematic-0.17.11_amd64.deb` command.
  2. Show the link (or try to run it) with `ls -la /usr/bin/kitematic`.

**Comment by Trackhe** [comment]
thanks for report the issue. and srry for the late response. can you fix it temporarly for you? i fix it in the next release! Thank You!

**Comment by PhoneixS** [comment]
Yes, I only have to make the link manually so no problem.

**Comment by Trackhe** [comment]
@PhoneixS i want to fix this in the next update. this weekend but it is a bug? can you run this installer without errors?

**Comment by PhoneixS** [comment]
With version v0.18.01 it installs correctly. Good work.
